version: "3.5"

services:
  app:
    build: .
    container_name: "price-tracker-api"
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: "price-tracker-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coin_tracker  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "nest-pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
